name: flights
favicon: null
layout_spectrum: 0.6838388463947922
typography_spectrum: 0.15818163403309882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.33934012637473643
purpose:
  - name: awareness
    item: null
    url: null
