typography_spectrum: 0.15818163403309882
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.33934012637473643
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6838388463947922
analytics:
  google: null
  facebook: null
  twitter: null
name: flights
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
